// ReviewData.js
const reviews = [
  {
    id: 1,
    author: "Sarah Johnson",
    avatar: "https://api.uifaces.co/our-content/donated/xZ4wg2Xj.jpg",
    rating: 5,
    date: "2025-08-13",
    title: "Absolutely phenomenal quality!",
    content: "The attention to detail is remarkable. From the packaging to the product itself, everything screams premium quality. I'm thoroughly impressed!",
    verified: true,
    productId: 6,
    badge: "Top Review",
    likes: 234,
    comments: 18,
    helpful: 156
  },
  {
    id: 2,
    author: "Michael Chen",
    avatar: "https://api.uifaces.co/our-content/donated/FJkauyEa.jpg",
    rating: 5,
    date: "2025-08-12",
    title: "Gaming has never been better!",
    content: "The PS5 controller's haptic feedback is mind-blowing. Every game feels more immersive. Plus, the battery life is impressive!",
    verified: true,
    productId: 1,
    badge: "Verified Pro",
    likes: 189,
    comments: 12,
    helpful: 142
  },
  {
    id: 3,
    author: "Emma Thompson",
    avatar: "https://api.uifaces.co/our-content/donated/AW-Gkq4o.jpg",
    rating: 5,
    date: "2025-08-11",
    title: "Worth every penny!",
    content: "The modern design perfectly complements my living space. Assembly was a breeze, and the quality is outstanding. Highly recommend!",
    verified: true,
    productId: 16,
    badge: "Elite Customer",
    likes: 167,
    comments: 15,
    helpful: 98
  },
  {
    id: 4,
    author: "Alex Rivera",
    avatar: "https://api.uifaces.co/our-content/donated/N7WEqL6w.jpg",
    rating: 3,
    date: "2025-08-13",
    title: "Decent but could be better",
    content: "The product is okay, but I expected more for the price. Delivery was quick though.",
    verified: false,
    productId: 3,
    badge: "New Reviewer",
    likes: 45,
    comments: 8,
    helpful: 32
  },
  {
    id: 5,
    author: "David Kim",
    avatar: "https://api.uifaces.co/our-content/donated/KtCFjlD4.jpg",
    rating: 4,
    date: "2025-08-12",
    title: "Great value for money",
    content: "Really happy with this purchase. The quality is good and it arrived earlier than expected.",
    verified: true,
    productId: 15,
    badge: "Verified Purchase",
    likes: 122,
    comments: 11,
    helpful: 89
  },
  {
    id: 6,
    author: "Maria Garcia",
    avatar: "https://api.uifaces.co/our-content/donated/PABqiMGo.jpg",
    rating: 2,
    date: "2025-08-11",
    title: "Not what I expected",
    content: "The color is different from what was shown in the pictures. Disappointed with the purchase.",
    verified: false,
    productId: 7,
    badge: "Regular Customer",
    likes: 34,
    comments: 21,
    helpful: 45
  },
  {
    id: 7,
    author: "James Wilson",
    avatar: "https://api.uifaces.co/our-content/donated/VUMBKh1U.jpg",
    rating: 5,
    date: "2025-08-13",
    title: "Exceeded expectations!",
    content: "Absolutely fantastic product! The build quality is superb and it works perfectly.",
    verified: true,
    productId: 12,
    badge: "Tech Expert",
    likes: 198,
    comments: 16,
    helpful: 167
  },
  {
    id: 8,
    author: "Sophie Chen",
    avatar: "https://api.uifaces.co/our-content/donated/6MWJxqS4.jpg",
    rating: 4,
    date: "2025-08-12",
    title: "Very satisfied customer",
    content: "Great product overall. The only minor issue is the setup takes a bit longer than expected.",
    verified: true,
    productId: 11,
    badge: "Smart Home Enthusiast",
    likes: 156,
    comments: 14,
    helpful: 123
  },
  {
    id: 9,
    author: "Tom Anderson",
    avatar: "https://api.uifaces.co/our-content/donated/n4Ngwvi7.jpg",
    rating: 1,
    date: "2025-08-11",
    title: "Don't waste your money",
    content: "Product arrived damaged and customer service was unhelpful. Would not recommend.",
    verified: false,
    productId: 5,
    badge: "New Customer",
    likes: 23,
    comments: 31,
    helpful: 67
  },
  {
    id: 10,
    author: "Olivia Brown",
    avatar: "https://api.uifaces.co/our-content/donated/TYv4xZFA.jpg",
    rating: 5,
    date: "2025-08-10",
    title: "Love it!",
    content: "This smartwatch exceeded my expectations in both style and functionality.",
    verified: true,
    productId: 15,
    badge: "Top Review",
    likes: 145,
    comments: 9,
    helpful: 112
  },
  {
    id: 11,
    author: "Liam Scott",
    avatar: "https://api.uifaces.co/our-content/donated/gpU7kV5k.jpg",
    rating: 4,
    date: "2025-08-09",
    title: "Good value",
    content: "Comfortable running shoes, lightweight and durable.",
    verified: true,
    productId: 24,
    badge: "Verified Purchase",
    likes: 88,
    comments: 10,
    helpful: 65
  },
  {
    id: 12,
    author: "Mia Patel",
    avatar: "https://api.uifaces.co/our-content/donated/1Rj8hP5k.jpg",
    rating: 5,
    date: "2025-08-08",
    title: "Fantastic camera!",
    content: "The DSLR camera produces stunning images, perfect for both beginners and pros.",
    verified: true,
    productId: 13,
    badge: "Elite Customer",
    likes: 132,
    comments: 12,
    helpful: 98
  },
  {
    id: 13,
    author: "Noah Wright",
    avatar: "https://api.uifaces.co/our-content/donated/6EtJxqS3.jpg",
    rating: 3,
    date: "2025-08-07",
    title: "Average quality",
    content: "The non-stick pan works fine but the handle feels a bit flimsy.",
    verified: false,
    productId: 17,
    badge: "Regular Customer",
    likes: 45,
    comments: 6,
    helpful: 28
  },
  {
    id: 14,
    author: "Isabella Martinez",
    avatar: "https://api.uifaces.co/our-content/donated/7N9kP4u8.jpg",
    rating: 5,
    date: "2025-08-06",
    title: "Beautiful dress!",
    content: "The summer dress fits perfectly and looks amazing.",
    verified: true,
    productId: 7,
    badge: "Top Review",
    likes: 176,
    comments: 11,
    helpful: 140
  },
  {
    id: 15,
    author: "Ethan Davis",
    avatar: "https://api.uifaces.co/our-content/donated/8VJkQp5w.jpg",
    rating: 4,
    date: "2025-08-05",
    title: "Comfortable shirt",
    content: "Men's cotton shirt is breathable and fits well. Good quality!",
    verified: true,
    productId: 6,
    badge: "Verified Purchase",
    likes: 97,
    comments: 5,
    helpful: 78
  },
  {
    id: 16,
    author: "Charlotte Lewis",
    avatar: "https://api.uifaces.co/our-content/donated/9PXkQp7x.jpg",
    rating: 5,
    date: "2025-08-04",
    title: "Perfect sofa",
    content: "The 3-seater sofa is super comfortable and the color matches my living room perfectly.",
    verified: true,
    productId: 16,
    badge: "Elite Customer",
    likes: 143,
    comments: 13,
    helpful: 110
  },
  {
    id: 17,
    author: "Alexander Hall",
    avatar: "https://api.uifaces.co/our-content/donated/2XJkVq5u.jpg",
    rating: 4,
    date: "2025-08-03",
    title: "Good performance",
    content: "Gaming laptop runs smoothly, handles heavy games easily.",
    verified: true,
    productId: 12,
    badge: "Tech Expert",
    likes: 125,
    comments: 14,
    helpful: 101
  },
  {
    id: 18,
    author: "Amelia King",
    avatar: "https://api.uifaces.co/our-content/donated/4TUkRp9z.jpg",
    rating: 3,
    date: "2025-08-02",
    title: "Okay tablet",
    content: "Android tablet is decent for browsing and videos but lags sometimes.",
    verified: false,
    productId: 14,
    badge: "Regular Customer",
    likes: 56,
    comments: 8,
    helpful: 34
  },
  {
    id: 19,
    author: "Daniel Moore",
    avatar: "https://api.uifaces.co/our-content/donated/5WJkQp6v.jpg",
    rating: 5,
    date: "2025-08-01",
    title: "Great microwave",
    content: "Heats food quickly and works perfectly. Very satisfied.",
    verified: true,
    productId: 20,
    badge: "Top Review",
    likes: 102,
    comments: 7,
    helpful: 90
  },
  {
    id: 20,
    author: "Grace Lee",
    avatar: "https://api.uifaces.co/our-content/donated/3YJkQp8w.jpg",
    rating: 4,
    date: "2025-07-31",
    title: "Nice bedsheet",
    content: "Queen bedsheet is soft and comfortable, colors are vibrant.",
    verified: true,
    productId: 19,
    badge: "Verified Purchase",
    likes: 89,
    comments: 6,
    helpful: 72
  }
];

export default reviews;
